server:
  port: 9527
spring:
  application:
    name: cloud-gateway #服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能 通过服务名进行路由
      routes:
      - id: payment_routh #路由的id
#        uri: http://localhost:8001
        uri: lb://cloud-payment-service
#测试数据123
        predicates:
        - Path=/payment/get/**   #断言 路径相匹配的进行路由
      - id: payment_routh2 #路由的id
#        uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/getLb/**   #断言 路径相匹配的进行路由
        - Header=X-Request-Id, \d+
#        - After=2022-03-20T17:29:57.421+08:00[Asia/Shanghai]
#        - Cookie=username,zzxx
#      - id: payment_routh3 #路由的id
#        uri: http://news.baidu.com
#        predicates:
#        - Path=/guonei   #断言 路径相匹配的进行路由

eureka:
  instance:
    instance-id: cloud-gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/